"""
Django settings for library_project project.

Generated by 'django-admin startproject' using Django 4.x.

For more information on this file, see
https://docs.djangoproject.com/en/4.x/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.x/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.x/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9x@3!k8p^mz4vq#l5h&j@n$w6r*t2y+u7i1o0p4a8s(d=f-g+c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'library_app',  # Наше приложение для системы управления библиотекой
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'library_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Кастомные шаблоны проекта
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # Для медиа файлов
            ],
        },
    },
]

WSGI_APPLICATION = 'library_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.x/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.x/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.x/topics/i18n/

LANGUAGE_CODE = 'ru-ru'  # Русский язык

TIME_ZONE = 'Europe/Moscow'  # Московское время

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.x/howto/static-files/

STATIC_URL = '/static/'

# Дополнительные директории со статическими файлами
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Директория для сбора статических файлов (для продакшена)
STATIC_ROOT = BASE_DIR / "staticfiles"


# Media files (User uploads)
# https://docs.djangoproject.com/en/4.x/topics/files/

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/4.x/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication settings

# URL для перенаправления неавторизованных пользователей
LOGIN_URL = 'login'

# URL после успешного входа
LOGIN_REDIRECT_URL = 'catalog'

# URL после выхода из системы
LOGOUT_REDIRECT_URL = 'home'


# Session settings

# Время жизни сессии в секундах (2 недели = 1209600 секунд)
SESSION_COOKIE_AGE = 1209600

# Сохранять сессию при каждом запросе
SESSION_SAVE_EVERY_REQUEST = True

# Имя куки для сессии
SESSION_COOKIE_NAME = 'library_sessionid'

# Безопасная куки (только через HTTPS)
SESSION_COOKIE_SECURE = False  # True для продакшена с HTTPS

# HttpOnly куки (недоступна через JavaScript)
SESSION_COOKIE_HTTPONLY = True

# SameSite атрибут куки
SESSION_COOKIE_SAMESITE = 'Lax'


# CSRF settings

CSRF_COOKIE_NAME = 'library_csrftoken'

CSRF_COOKIE_HTTPONLY = False  # True для большей безопасности

CSRF_TRUSTED_ORIGINS = []


# Messages framework

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',  # 'danger' для совместимости с Bootstrap
}


# File upload settings

# Максимальный размер загружаемого файла (10 МБ)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760

# Максимальный размер данных в запросе (15 МБ)
DATA_UPLOAD_MAX_MEMORY_SIZE = 15728640

# Разрешенные расширения для загрузки (можно добавить валидацию в формах)
ALLOWED_IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.webp']

# Максимальный размер изображений (в байтах)
MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5 МБ


# Email settings (для отправки уведомлений)

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Для продакшена использовать:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@example.com'
# EMAIL_HOST_PASSWORD = 'your-password'


# Security settings (для продакшена раскомментировать)

# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True
# X_FRAME_OPTIONS = 'DENY'
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True


# Logging configuration

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
            'level': 'INFO',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'library_app': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# Custom user settings

# Максимальное количество книг, которое можно взять одновременно
MAX_BOOKS_PER_READER = 5

# Срок выдачи книги по умолчанию (в днях)
DEFAULT_BOOK_LOAN_PERIOD = 14

# Штраф за просрочку (в рублях за день)
FINE_PER_DAY = 10

# Показывать ли напоминания за N дней до возврата
REMINDER_DAYS_BEFORE = 3


# Cache settings (опционально)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-library-cache',
    }
}

# Кэширование для популярных книг на главной странице
CACHE_TIMEOUT_POPULAR_BOOKS = 300  # 5 минут